# pyproject.toml
[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.poetry.dependencies]
python = "^3.9"
streamlit = "^1.23.1"
numpy = "^1.26.2"
pandas = "^2.1.4"
matplotlib = "^3.8.2"
scipy = "^1.11.4"
